### ISSUE TITLE
Automatic image building

### ISSUE THREAD

**Issue by TiagoCavalcanteTrindade** [Mathics3/mathics-omnibus#2]
@rocky I think it'd be nice [and less time consuming] to have a [automatic image building](https://github.com/marketplace/actions/build-and-push-docker-images) which runs [every week](https://jasonet.co/posts/scheduled-actions/) if it don't overrun the minute quota.

**Comment by rocky** [comment]
The build process isn't stable right now; nor is it feature wise where I'd like it to be. Things have been changing too rapidly. 

Automating release of something that is in a somewhat chaotic state I think will add to yet another source of flakiness. 

We don't _have_ to make a new docker image every week, we just do when I think it is warranted. And we make PyPI/github releases when we think it is right to release. 

Normally, I'd say well if this is something you want to do, go for it. But I know it is just going to detract from getting things stable. And the images might be unstable (automatically) too.

I think this is a good idea for down the line, but just not right now.

**Comment by TiagoCavalcanteTrindade** [comment]
Ok, this makes sense, maybe [build the image in every release](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release)  of the other mathics repositories?

Also @rocky when I try to build with the following command:
```sh
cd docker && docker build -t mathics .
```
It gives the following error: `/bin/sh: 1: cd: can't cd to src/mathics-django`. I saw that in the `Dockerfile` doens't looks to download Mathics Django from anywhere.

And when I try to build with the following command:
```sh
cd docker && docker build -f Dockerfile-dev -t mathics .
```
It gives the following error:
```
#22 2.134 Obtaining mathicsscript from git+git://github.com/Mathics3/mathicsscript#egg=mathicsscript
#22 2.135   Cloning git://github.com/Mathics3/mathicsscript to ./src/mathicsscript
#22 2.135   Running command git clone -q git://github.com/Mathics3/mathicsscript /usr/src/app/src/mathicsscript
#22 4.229     ERROR: Command errored out with exit status 1:
#22 4.229      command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/usr/src/app/src/mathicsscript/setup.py'"'"'; __file__='"'"'/usr/src/app/src/mathicsscript/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
#22 4.229          cwd: /usr/src/app/src/mathicsscript/
#22 4.229     Complete output (5 lines):
#22 4.229     Traceback (most recent call last):
#22 4.229       File "<string>", line 1, in <module>
#22 4.229       File "/usr/src/app/src/mathicsscript/setup.py", line 55, in <module>
#22 4.229         for line in open("requirements-full.txt").read().split("\n"):
#22 4.229     FileNotFoundError: [Errno 2] No such file or directory: 'requirements-full.txt'
```

**Comment by rocky** [comment]
We use docker-compose, not docker. 

Install `remake` and type `remake --tasks`. 

In general, just use the Makefile targets.

**Comment by rocky** [comment]
@TiagoCavalcanteTrindade here is something I bet you could fix up is getting the SVG tick marks aligned in `Plot[]`. For example look at

```
Plot[Sin[x] Cos[1 + x], {x, 0, 2 Pi},PlotRange->{-1,1}]
```

and you'll see things are a real mess.  

If this is of interest to you, I'll try to remember the last change I made to get these to at least start appearing again.

---

I have given up for the day trying to get DensityPlot working. The main problem I have is on the Mathics end in figuring out how to get the vertex color information at the place where it is needed in the svg formatter.

**Comment by rocky** [comment]
Change that. I remember now those tick marks are fine. It is the lines extending below the line in the bar charts, e.g. 

```
BarChart[{{1, 2, 3}, {2, 3, 4}}]
```

and I am not sure the one extending bellow the line in 

```
Plot[Abs[Sin[t] / (t + 1)], {t, 0, 4 Pi}, Mesh->Full, PlotRange->{0, 1 / 2}]
```
is that useful too. Dunno - what do you think?

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky yes, the tick numbers are all over the tick lines (even in `BarChart` they're too close), also what do you think of increasing the opacity?

![image](https://user-images.githubusercontent.com/62714153/122625027-6fc90f80-d079-11eb-9820-76488edefe68.png)

@rocky changing the style `text-anchor` to `end` in Mathics Core should solve this problem (I made it for -0.5).

Also seeing this now I remembered that we need to increase the responsiveness for smaller screens for `svg`. I can do it by the same approach used by `drawGraphics3d`.

**Comment by rocky** [comment]
> @rocky yes, the tick numbers are all over the tick lines (even in `BarChart` they're too close), also what do you think of increasing the opacity?

When it comes to style issues, I'll go with whatever the other person or person asking things. 

> 
> ![image](https://user-images.githubusercontent.com/62714153/122625027-6fc90f80-d079-11eb-9820-76488edefe68.png)
> 
> @rocky changing the style `text-anchor` to `end` in Mathics Core should solve this problem (I made it for -0.5).
> 

Ok. Please put in a PR for that. 

> Also seeing this now I remembered that we need to increase the responsiveness for smaller screens for `svg`. I can do it by the same approach used by `drawGraphics3d`.

Ok. Please do that too. Thanks!
